config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root                                'home#index'
    get 'index',                    to: 'home#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'

    resources :products,            only: :show
    resources :categories,          only: :show
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/option_type_decorator.rb
Spree::OptionType.class_eval do
  def self.fetch_option_values(color_or_size)
    joins(:option_values).where(spree_option_types: { presentation: color_or_size }).pluck("spree_option_values.presentation")
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  NUMBER_OF_RELATED_PRODUCTS = 4

  def related_products_ids
    Spree::Product.joins(:classifications).where(spree_products_taxons: { taxon_id: taxons }).
      where.not(id: id).distinct.pluck(:id).sample(NUMBER_OF_RELATED_PRODUCTS)
  end

  def self.sort_by_option(option)
    option ||= :new
    reorder(nil).send("sort_by_#{option}")
  end

  scope :includes_images_and_price, -> { includes(master: [:images, :default_price]) }

  scope :related_products_of, -> (product) do
    includes(master: [:images, :default_price]).where(id: product.related_products_ids)
  end

  # 購入可能な商品を新しい順に商品を取得する
  scope :new_arrival, -> { where("available_on <= ?", DateTime.now).order(available_on: :desc) }

  scope :filter_by_option, -> (option_value) do
    joins(variants: :option_values).where(spree_option_values: { presentation: option_value }) if option_value.present?
  end

  scope :sort_by_new, -> { order(available_on: :desc) }

  scope :sort_by_old, -> { order(available_on: :asc) }

  scope :sort_by_price_asc, -> { order("spree_prices.amount ASC") }

  scope :sort_by_price_desc, -> { order("spree_prices.amount DESC") }
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  def self.count_products(products_ids)
    joins(:option_values).where(product_id: products_ids).group("spree_option_values.presentation").count("DISTINCT product_id")
  end

  scope :fetch_variants_of, -> (products_ids, option_value) do
    joins(:option_values).where(product_id: products_ids, spree_option_values: { presentation: option_value })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.includes(root: :children)
    @products = Spree::Product.in_taxon(@taxon).includes_images_and_price.filter_by_option(params[:option_value]).sort_by_option(params[:sort])
    if params[:option_type] == "color"
      @variants = Spree::Variant.fetch_variants_of(@products.pluck(:id), params[:option_value])
    end
    @view_type = params[:view_type] == "list" ? "list" : "grid"
    @sizes = Spree::OptionType.fetch_option_values("Size")
    @colors = Spree::OptionType.fetch_option_values("Color")
    @the_number_of_products_in_option = Spree::Variant.count_products(@products.pluck(:id))
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  def index
    @new_arrival_products = Spree::Product.includes_images_and_price.new_arrival
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  def show
    @product = Spree::Product.find(params[:id])
    @properties = @product.product_properties.includes(:property)
    @shipping_methods = @product.shipping_category.shipping_methods
    @related_products = Spree::Product.related_products_of(@product)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返します。
  def full_title(page_title = "")
    base_title = "BIGBAG Store"
    return base_title if page_title.empty?

    "#{page_title} | #{base_title}"
  end
end

app/views/layouts/_copy_right.html.erb
<!-- COPY RIGHT -->
<div class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016 Copyright Bigbag Store Bootstrap Template by <a target="_blank" href="http://www.iamabdus.com/">Abdus</a>.</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
          <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
          <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- GOOGLE FONT -->
<%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">

  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
            <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
            <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li><span><a data-toggle="modal" href='#login'>Log in</a><small>or</small><a data-toggle="modal" href='#signup'>Create an account</a></span></li>
            <li class="dropdown searchBox">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <span class="input-group">
                    <input type="text" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span class="input-group-addon" id="basic-addon2">Search</span>
                  </span>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i>$0</a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>Item(s) in your cart</li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <div class="btn-group" role="group" aria-label="...">
                    <button type="button" class="btn btn-default">Shopping Cart</button>
                    <button type="button" class="btn btn-default">Checkout</button>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("img/logo.png", alt: ""), potepan_index_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", potepan_index_path %></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
            <ul class="dropdown-menu row">
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled" id="link_to_grid_view">
                  <li>Products Grid View</li>
                  <li><%= link_to "All Categories", potepan_category_path(Spree::Taxon.first.id, view_type: "grid") %></li>
                  <li><a href="#">Products Sidebar Right</a></li>
                  <li><a href="#">Products 3 Columns V1</a></li>
                  <li><a href="#">Products 3 Columns V2</a></li>
                  <li><a href="#">Products 4 Columns</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled" id="link_to_list_view">
                  <li>Products List View</li>
                  <li><%= link_to "All Categories", potepan_category_path(Spree::Taxon.first.id, view_type: "list") %></li>
                  <li><a href="#">Products Sidebar Right</a></li>
                  <li class="listHeading">Others</li>
                  <li class="active"><a href="#">Single Product</a></li>
                  <li><a href="#">Cart Page</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Checkout</li>
                  <li><a href="#">Step 1 - Address</a></li>
                  <li><a href="#">Step 2 - Shipping</a></li>
                  <li><a href="#">Step 3 - Payment</a></li>
                  <li><a href="#">Step 4 - Payment</a></li>
                  <li><a href="#">Order Complete</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">pages</a>
            <ul class="dropdown-menu dropdown-menu-left">
              <li><a href="#">About Us</a></li>
              <li><a href="#">Register</a></li>
              <li><a href="#">Register or Login</a></li>
              <li><a href="#">Login</a></li>
              <li><a href="#">Password Recovery</a></li>
              <li><a href="#">Privacy Policy</a></li>
              <li><a href="#">Terms &amp; Conditions</a></li>
              <li><a href="#">Coming Soon</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">blog</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="blog_right_sidebar.html">Right Sidebar</a></li>
              <li><a href="blog_left_sidebar.html">Left Sidebar</a></li>
              <li><a href="blog_single_right_sidebar.html">Single Right Sidebar</a></li>
              <li><a href="blog_single_left_sidebar.html">Single Left Sidebar</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="#">Dashboard</a></li>
              <li><a href="#">Profile</a></li>
              <li><a href="#">All Orders</a></li>
              <li><a href="#">Single Order</a></li>
              <li><a href="#">Wishlist</a></li>
              <li><a href="#">Address</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

</div>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= render "layouts/head" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <div class="main-wrapper">
      <%= render "layouts/header" %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= render "layouts/copy_right" %>
    </div>
    <%= render "layouts/modals" %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_categories_tree.html.erb
<%# 商品のカテゴリーツリーを作成する %>
<div class="panel panel-default" id="categories_tree">
  <div class="panel-heading">商品カテゴリー</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">

        <%# taxonomyごとにカテゴリーツリーを作成する %>
        <% @taxonomies.each do |taxonomy| %>
          <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#<%= "taxonomy-#{taxonomy.id}" %>"><%= taxonomy.name %><i class="fa fa-plus"></i></a>
            <ul id="<%= "taxonomy-#{taxonomy.id}" %>" class="collapse collapseItem">
              <% taxonomy.root.children.each do |taxon| %>
                <li>
                  <%# taxonが子要素を持っていなければ、taxonへのリンクを表示 %>
                  <% if taxon.leaf? %>
                    <%= link_to potepan_category_path(taxon.id) do %>
                      <i class="fa fa-caret-right" aria-hidden="true"></i><%= "#{taxon.name} (#{taxon.products.count})" %>
                    <% end %>
                  <%# taxonが子要素を持っていれば、そのカテゴリーツリーを作成 %>
                  <% else %>
                    <a href="javascript:;" data-toggle="collapse" data-target="#<%= "taxon-#{taxon.id}" %>"><%= taxon.name %><i class="fa fa-plus"></i></a>
                    <ul id="<%= "taxon-#{taxon.id}" %>" class="collapse collapseItem">
                      <li>
                        <% taxon.leaves.each do |leaf| %>
                          <%= link_to potepan_category_path(leaf.id), class: "leaf" do %>
                            <i class="fa fa-caret-right" aria-hidden="true"></i><%= "#{leaf.name} (#{leaf.products.count})" %>
                          <% end %>
                        <% end %>
                      </li>
                    </ul>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_color_filter.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <% @colors.each do |color| %>
        <li>
          <%= link_to potepan_category_path(@taxon.id, option_type: "color", option_value: color, sort: params[:sort]) do %>
            <%= "#{color} (#{@the_number_of_products_in_option[color] ||= 0})" %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/categories/_grid_view.html.erb
<div class="row equal-height" id="grid_view">
  <% if @products.empty? %>
    <div class="col-md-8 col-md-offset-2">
      <div class="products-not-found">
        <h3>商品が見つかりませんでした</h3>
      </div>
    </div>
  <% end %>
  <% @products.each_with_index do |product, i| %>
    <div class="col-sm-4 col-xs-12">
      <div class="productBox">
        <div class="productImage clearfix">
          <% if params[:option_type] == "color" %>
            <%= image_tag(@variants[i].display_image.attachment.url, alt: "products-img") %>
          <% else %>
            <%= image_tag(product.display_image.attachment.url, alt: "products-img") %>
          <% end %>
          <div class="productMasking">
            <ul class="list-inline btn-group" role="group">
              <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
              <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
              <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
            </ul>
          </div>
        </div>
        <div class="productCaption clearfix">
          <%= link_to potepan_product_path(product.id) do %>
            <h5><%= product.name %></h5>
          <% end %>
          <h3><%= product.display_price %></h3>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/categories/_list_view.html.erb
<div class="row productListSingle" id="list_view">
  <% if @products.empty? %>
    <div class="col-md-8 col-md-offset-2">
      <div class="products-not-found">
        <h3>商品が見つかりませんでした</h3>
      </div>
    </div>
  <% end %>
  <% @products.each_with_index do |product, i| %>
    <div class="col-xs-12">
      <div class="media">
        <div class="media-left">
          <% if params[:option_type] == "color" %>
            <%= image_tag(@variants[i].display_image.attachment.url, class: "media-object", alt: "Image") %>
          <% else %>
            <%= image_tag(product.display_image.attachment.url, class: "media-object", alt: "Image") %>
          <% end %>
          <span class="maskingImage"><a data-toggle="modal" href=".quick-view" class="btn viewBtn">Quick View</a></span>
        </div>
        <div class="media-body">
          <h4 class="media-heading"><a href="<%= potepan_product_path(product.id) %>"><%= product.name %></a></h4>
          <p><%= product.description %></p>
          <h3><%= product.display_price %></h3>
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-default" data-toggle="modal" data-target=".login-modal"><i class="fa fa-heart" aria-hidden="true"></i></button>
            <button type="button" class="btn btn-default" onclick="location.href='cart-page.html';"><i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/categories/_price_slider.html.erb
<%# 商品価格のスライダー %>
<div class="panel panel-default priceRange">
  <div class="panel-heading">値段から探す</div>
  <div class="panel-body clearfix">
    <div class="price-slider-inner">
      <span class="amount-wrapper">
        <input type="text" id="price-amount-1" readonly>
        <strong>-</strong>
        <input type="text" id="price-amount-2" readonly>
      </span>
      <div id="price-range"></div>
    </div>
    <input class="btn btn-default" type="submit" value="絞り込む">
  </div>
</div>

app/views/potepan/categories/_size_filter.html.erb
<%# 商品サイズのフィルター %>
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <ul class="list-unstyled clearfix">
      <% @sizes.each do |size| %>
        <li>
          <%= link_to potepan_category_path(@taxon.id, option_type: "size", option_value: size, sort: params[:sort]) do %>
            <%= "#{size} (#{@the_number_of_products_in_option[size] ||= 0})" %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/categories/show.html.erb
<%= provide(:title, @taxon.name) %>

<%= render "shared/light_section_top", page_title: @taxon.name %>

<%# MAIN CONTENT SECTION %>
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <%= render "categories_tree" %>
        <%= render "price_slider" %>
        <%= render "color_filter" %>
        <%= render "size_filter" %>
      </div>

      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <%= form_tag(potepan_category_path(params[:id]), method: :get) do %>
              <%= select_tag "sort", options_for_select({"新着順": "new","古い順": "old", "価格の安い順": "price_asc", "価格の高い順": "price_desc"}, selected: params[:sort]), onchange: "this.form.submit()", class: "select-drop" %>
              <%= hidden_field_tag(:option_type, params[:option_type]) %>
              <%= hidden_field_tag(:option_value, params[:option_value]) %>
              <%= submit_tag "選択", name: "", class: "btn btn-primary" %>
            <% end %>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" id="switching_view_btn" role="group">
              <%= link_to potepan_category_path(@taxon.id, view_type: "grid", option_type: params[:option_type], option_value: params[:option_value], sort: params[:sort]), id: "grid_btn", class: "btn btn-default #{"active" if @view_type == "grid"}", remote: true do %>
                <i class="fa fa-th" aria-hidden="true"></i><span>Grid</span>
              <% end %>
              <%= link_to potepan_category_path(@taxon.id, view_type: "list", option_type: params[:option_type], option_value: params[:option_value], sort: params[:sort]), id: "list_btn", class: "btn btn-default #{"active" if @view_type == "list"}", remote: true do %>
                <i class="fa fa-th-list" aria-hidden="true"></i><span>List</span>
              <% end %>
            </div>
          </div>
        </div>
        
        <div id="rendering_products">
          <% if @view_type == "grid" %>
            <%= render "grid_view" %>
          <% else %>
            <%= render "list_view" %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</section>

<%= render "shared/light_section_bottom" %>

app/views/potepan/home/_popular_categories.html.erb
<%# popular_categories %>
<div class="row featuredCollection">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>人気カテゴリー（写真はイメージです）</h4>
    </div>
  </div>
  <div class="col-sm-4 col-xs-12">
    <div class="thumbnail" onclick="location.href='<%= potepan_product_path(3) %>';">
      <div class="imageWrapper">
        <%= image_tag("home/featured-collection/featured-collection-01.jpg", :alt => "feature-collection-image") %>
        <div class="masking">
          <%= link_to "View Clothing", potepan_category_path(5), class: "btn viewBtn" %>
        </div>
      </div>
      <div class="caption">
        <h4>Clothing</h4>
      </div>
    </div>
  </div>
  <div class="col-sm-4 col-xs-12">
    <div class="thumbnail" onclick="location.href='<%= potepan_product_path(1) %>';">
      <div class="imageWrapper">
        <%= image_tag("home/featured-collection/featured-collection-02.jpg", :alt => "feature-collection-image") %>
        <div class="masking">
          <%= link_to "View Bags", potepan_category_path(3), class: "btn viewBtn" %>
        </div>
      </div>
      <div class="caption">
        <h4>Bags</h4>
      </div>
    </div>
  </div>
  <div class="col-sm-4 col-xs-12">
    <div class="thumbnail" onclick="location.href='<%= potepan_product_path(8) %>';">
      <div class="imageWrapper">
        <%= image_tag("home/featured-collection/featured-collection-03.jpg", :alt => "feature-collection-image") %>
        <div class="masking">
          <%= link_to "View Mags", potepan_category_path(4), class: "btn viewBtn" %>
        </div>
      </div>
      <div class="caption">
        <h4>Mags</h4>
      </div>
    </div>
  </div>
</div>

app/views/potepan/home/_products_area.html.erb
<%# 新着商品をカルーセルで順番に表示する %>
<div class="slide">
  <div class="productImage clearfix">
    <%= image_tag(product.display_image.attachment.url, alt: "products-img") %>
    <div class="productMasking">
      <ul class="list-inline btn-group" role="group">
        <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
        <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
        <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
      </ul>
    </div>
  </div>
  <div class="productCaption clearfix">
    <%= link_to potepan_product_path(product.id) do %>
      <h5><%= product.name %></h5>
    <% end %>
    <h3><%= product.display_price %></h3>
  </div>
</div>

app/views/potepan/products/_related_products.html.erb
<%# 関連商品を順番に表示する %>
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="productBox related_product">
    <div class="productImage clearfix">
      <%= image_tag(product.display_image.attachment.url, alt: "products-img") %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path(product.id) do %>
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_light_section_top.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader" id="light_section_top">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= page_title %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_index_path %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= page_title %></li>
        </ol>
      </div>
    </div>
  </div>
</section>